In [83]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib as plt
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt2
import seaborn as sns
from sklearn.preprocessing import StandardScaler

In [84]:
%matplotlib inline

df = pd.read_csv("O:/Data Quality/Data Analytics/research/2020/6. Minerva/4. results/MIN101C07_101_mk_data_for_ML 12 April 2021.csv") #Reading the dataset in a dataframe using Pandas

df.head(10)



USUBJID         _NAME_               _LABEL_   V_1   V_3  \
0  MIN-101C07-0130-0001      AVAL_NSFS        Analysis Value  23.0  21.0   
1  MIN-101C07-0130-0001       CHG_NSFS  Change from Baseline   NaN   NaN   
2  MIN-101C07-0130-0001  AVAL_PANSSTOT        Analysis Value  65.0  71.0   
3  MIN-101C07-0130-0001   CHG_PANSSTOT  Change from Baseline   NaN   NaN   
4  MIN-101C07-0130-0002      AVAL_NSFS        Analysis Value  22.0  23.0   
5  MIN-101C07-0130-0002       CHG_NSFS  Change from Baseline   NaN   NaN   
6  MIN-101C07-0130-0002  AVAL_PANSSTOT        Analysis Value  68.0  72.0   
7  MIN-101C07-0130-0002   CHG_PANSSTOT  Change from Baseline   NaN   NaN   
8  MIN-101C07-0130-0004      AVAL_NSFS        Analysis Value  28.0  28.0   
9  MIN-101C07-0130-0004       CHG_NSFS  Change from Baseline   NaN   NaN   

    V_7   V_9  V_10  V_11  
0  21.0  19.0  14.0  12.0  
1   0.0  -2.0  -7.0  -9.0  
2  64.0  58.0  62.0  60.0  
3  -7.0 -13.0  -9.0 -11.0  
4  12.0   9.0   8.0   8.0  
5 -11.0 -14.0 -15.0 -15.0  
6  53.0  48.0  48.0  47.0  
7 -19.0 -24.0 -24.0 -25.0  
8  19.0  29.0  24.0  18.0  
9  -9.0   1.0  -4.0 -10.0

In [105]:
tit = "Subset: AVAL_NSFS".title()
print(tit)
# subset
df=df[df["_NAME_"]=="AVAL_NSFS"]
display(df.head(10))


tit2 = "Numeric Variables Only".title()
print(tit2)
df=df.filter(regex='^V',axis=1)
display(df.head(10))
display(df.shape)

tit3 = "Exclude Missing".title()
print(tit3)
df=df.dropna()
display(df.head(10))
display(df.shape)

tit4 = "Standardized".title()
print(tit4)
#Standardize
clmns = ['V_1', 'V_3','V_7', 'V_9','V_10','V_11']
df2 = stats.zscore(df[clmns])
print(df2[1:10,])
display(df2.shape)

Subset: Aval_Nsfs


USUBJID     _NAME_         _LABEL_   V_1   V_3   V_7   V_9  \
0   MIN-101C07-0130-0001  AVAL_NSFS  Analysis Value  23.0  21.0  21.0  19.0   
4   MIN-101C07-0130-0002  AVAL_NSFS  Analysis Value  22.0  23.0  12.0   9.0   
8   MIN-101C07-0130-0004  AVAL_NSFS  Analysis Value  28.0  28.0  19.0  29.0   
12  MIN-101C07-0130-0006  AVAL_NSFS  Analysis Value  25.0  26.0  28.0  25.0   
16  MIN-101C07-0130-0010  AVAL_NSFS  Analysis Value  23.0  22.0  16.0  16.0   
20  MIN-101C07-0130-0015  AVAL_NSFS  Analysis Value  19.0  22.0   NaN   NaN   
24  MIN-101C07-0130-0017  AVAL_NSFS  Analysis Value  23.0  25.0  25.0  25.0   
28  MIN-101C07-0130-0023  AVAL_NSFS  Analysis Value  21.0  23.0  21.0   NaN   
32  MIN-101C07-0130-0026  AVAL_NSFS  Analysis Value  22.0  20.0  20.0  17.0   
36  MIN-101C07-0131-0001  AVAL_NSFS  Analysis Value  22.0  20.0  18.0  20.0   

    V_10  V_11  
0   14.0  12.0  
4    8.0   8.0  
8   24.0  18.0  
12  21.0  27.0  
16  18.0  18.0  
20   NaN   NaN  
24  27.0  23.0  
28   NaN  14.0  
32  17.0  17.0  
36  19.0  20.0

Numeric Variables Only


V_1   V_3   V_7   V_9  V_10  V_11
0   23.0  21.0  21.0  19.0  14.0  12.0
4   22.0  23.0  12.0   9.0   8.0   8.0
8   28.0  28.0  19.0  29.0  24.0  18.0
12  25.0  26.0  28.0  25.0  21.0  27.0
16  23.0  22.0  16.0  16.0  18.0  18.0
20  19.0  22.0   NaN   NaN   NaN   NaN
24  23.0  25.0  25.0  25.0  27.0  23.0
28  21.0  23.0  21.0   NaN   NaN  14.0
32  22.0  20.0  20.0  17.0  17.0  17.0
36  22.0  20.0  18.0  20.0  19.0  20.0

(513, 6)

No Missing


V_1   V_3   V_7   V_9  V_10  V_11
0   23.0  21.0  21.0  19.0  14.0  12.0
4   22.0  23.0  12.0   9.0   8.0   8.0
8   28.0  28.0  19.0  29.0  24.0  18.0
12  25.0  26.0  28.0  25.0  21.0  27.0
16  23.0  22.0  16.0  16.0  18.0  18.0
24  23.0  25.0  25.0  25.0  27.0  23.0
32  22.0  20.0  20.0  17.0  17.0  17.0
36  22.0  20.0  18.0  20.0  19.0  20.0
40  24.0  21.0  21.0  17.0  20.0  17.0
52  33.0  32.0  31.0  30.0  30.0  31.0

(371, 6)

Standardized
[[-0.96011203 -0.64874321 -3.10880472 -3.32617598 -3.16879955 -2.85687728]
 [ 0.9031917   0.95154755 -1.22553767  1.51973523  0.51582222 -0.69997563]
 [-0.02846016  0.31143125  1.19580569  0.55055299 -0.17504436  1.24123586]
 [-0.64956141 -0.96880136 -2.03265212 -1.63010706 -0.86591094 -0.69997563]
 [-0.64956141 -0.0086269   0.38869124  0.55055299  1.2066888   0.3784752 ]
 [-0.96011203 -1.60891766 -0.95649952 -1.3878115  -1.0961998  -0.9156658 ]
 [-0.96011203 -1.60891766 -1.49457582 -0.66092482 -0.63562208 -0.2685953 ]
 [-0.33901079 -1.28885951 -0.68746137 -1.3878115  -0.40533322 -0.9156658 ]
 [ 2.45594481  2.23178015  2.00292014  1.76203079  1.89755538  2.10399652]]


(371, 6)

In [106]:

#Cluster the data
km = KMeans(n_clusters=2, random_state=0).fit(df2)
labels = km.labels_
len(labels)
print(labels[1:10])

[0 1 1 0 1 0 0 0 1]


In [113]:
### glue tabk to original data
#df3['clusters']=labels
df['clusters'] = labels
df.head(10)

V_1   V_3   V_7   V_9  V_10  V_11  clusters
0   23.0  21.0  21.0  19.0  14.0  12.0         0
4   22.0  23.0  12.0   9.0   8.0   8.0         0
8   28.0  28.0  19.0  29.0  24.0  18.0         1
12  25.0  26.0  28.0  25.0  21.0  27.0         1
16  23.0  22.0  16.0  16.0  18.0  18.0         0
24  23.0  25.0  25.0  25.0  27.0  23.0         1
32  22.0  20.0  20.0  17.0  17.0  17.0         0
36  22.0  20.0  18.0  20.0  19.0  20.0         0
40  24.0  21.0  21.0  17.0  20.0  17.0         0
52  33.0  32.0  31.0  30.0  30.0  31.0         1

In [128]:
# add the column into list
clmns.extend(['clusters'])
print(df.columns)

Index(['V_1', 'V_3', 'V_7', 'V_9', 'V_10', 'V_11', 'clusters'], dtype='object')


In [117]:

#Lets analyze the clusters
print (df.groupby('clusters').mean().reset_index())

   clusters        V_1        V_3        V_7        V_9       V_10       V_11
0         0  23.121951  23.078049  21.126829  19.990244  18.975610  18.395122
1         1  27.524096  27.433735  26.554217  26.108434  25.198795  24.765060


In [134]:
#filter rows of original data
filtered_label = df[df["clusters"]==1]
print(filtered_label.head(10))
#Plotting the results

## can't plot scatter plot for >2 dimentions unless two dimentioins are specified
plt2.scatter(filtered_label[:,0] , filtered_label[:,1] , color = 'red')

plt.show()

      V_1   V_3   V_7   V_9  V_10  V_11  clusters
8    28.0  28.0  19.0  29.0  24.0  18.0         1
12   25.0  26.0  28.0  25.0  21.0  27.0         1
24   23.0  25.0  25.0  25.0  27.0  23.0         1
52   33.0  32.0  31.0  30.0  30.0  31.0         1
60   23.0  23.0  25.0  31.0  31.0  26.0         1
144  29.0  25.0  24.0  26.0  29.0  26.0         1
152  29.0  29.0  26.0  25.0  26.0  25.0         1
156  31.0  29.0  26.0  22.0  16.0  18.0         1
184  25.0  25.0  24.0  25.0  25.0  25.0         1
188  24.0  24.0  24.0  23.0  25.0  26.0         1


TypeError: '(slice(None, None, None), 0)' is an invalid key

In [126]:
# Visualize the clusters
#Getting unique labels
 
u_labels = np.unique(df["clusters"])
print(u_labels)
#plotting the results:
 
for i in u_labels:
    plt2.scatter(df[clusters == i , 0] , df[clusters == i , 1] , clusters = i)
plt2.legend()
plt2.show()

[0 1]


NameError: name 'clusters' is not defined